In [68]:
import pandas as pd

df = pd.read_csv('dataset.csv')

C:\Users\Prasanna\AppData\Local\Temp\ipykernel_11372\3058218090.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('dataset.csv')

In [69]:
df.head()

,Term ID,Class,Description,Status,Effective Date,Type,Notes,TM5,NCL Version
0,010-1886,10,Medical imaging apparatus for use in the field...,A,04/16/2020,GOODS,NaN,NaN,"""11-2020"""
1,010-1889,10,Medical diagnostic apparatus for testing {spec...,A,04/16/2020,GOODS,NaN,NaN,"""11-2020"""
2,028-4345,28,Balancing bird toys,A,04/16/2020,GOODS,Balancing bird toys are bird-shaped educationa...,T,"""11-2020"""
3,009-5776,9,Image intensifier tubes,A,04/16/2020,GOODS,Image intensifier tubes are a type of vacuum t...,T,"""11-2020"""
4,009-5779,9,Sunglasses for pets,A,04/16/2020,GOODS,Sunglasses is acceptable wording; further spec...,T,"""11-2020"""

In [70]:
df.dropna(subset=['Description', 'Class'], inplace=True)

In [71]:
X=df.drop('Class',axis=1)

In [72]:
y=df['Class']

In [73]:
X.shape

(68060, 8)

In [74]:
y.shape

(68060,)

In [75]:
import tensorflow as tf
tf.__version__

'2.15.0'

In [76]:
from tensorflow.keras.layers import Embedding
from tensorflow. keras.preprocessing. sequence import pad_sequences  #for equal length 
from tensorflow.keras.models import Sequential   
from tensorflow. keras.preprocessing.text import one_hot     #converting sentences into onehot representwtion given vocabulary size
from tensorflow. keras.layers import LSTM
from tensorflow. keras.layers import Dense

In [77]:
values_to_drop = ['A', '200', 'B']
df = df[~df['Class'].isin(values_to_drop)]

In [82]:
df["Class"][4851]

'20'

In [83]:
df

,Term ID,Class,Description,Status,Effective Date,Type,Notes,TM5,NCL Version
0,010-1886,10,Medical imaging apparatus for use in the field...,A,04/16/2020,GOODS,NaN,NaN,"""11-2020"""
1,010-1889,10,Medical diagnostic apparatus for testing {spec...,A,04/16/2020,GOODS,NaN,NaN,"""11-2020"""
2,028-4345,28,Balancing bird toys,A,04/16/2020,GOODS,Balancing bird toys are bird-shaped educationa...,T,"""11-2020"""
3,009-5776,9,Image intensifier tubes,A,04/16/2020,GOODS,Image intensifier tubes are a type of vacuum t...,T,"""11-2020"""
4,009-5779,9,Sunglasses for pets,A,04/16/2020,GOODS,Sunglasses is acceptable wording; further spec...,T,"""11-2020"""
...,...,...,...,...,...,...,...,...,...
68055,004-828,4,Fruitwood lump charcoal,A,08-08-2024,GOODS,"Lump charcoal, also known as natural hardwood ...",NaN,"""12-2024"""
68056,004-829,4,Hydrocarbon gas liquids (HGL) for use as fuel ...,A,08-08-2024,GOODS,NaN,NaN,"""12-2024"""
68057,004-830,4,Liquefied hydrocarbon gas (LHG) for use as fue...,A,08-08-2024,GOODS,NaN,NaN,"""12-2024"""
68058,004-831,4,Natural hardwood charcoal,A,08-08-2024,GOODS,"Natural hardwood charcoal is carbonized wood, ...",NaN,"""12-2024"""
68059,041-2804,41,Conducting entertainment exhibition events in ...,A,08-08-2024,SERVICES,NaN,NaN,"""12-2024"""

In [84]:
voc_size=5000

In [85]:
messages=X.copy()

In [86]:
messages['Description'][1]

'Medical diagnostic apparatus for testing {specify condition or subject matter tested, e.g., blood sugar levels, cancer cells, DNA, etc.} incorporating recorded operating system software'

In [87]:
messages.reset_index(inplace=True)

In [88]:
import nltk
import re
from nltk.corpus import stopwords

In [89]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Prasanna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [90]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    # print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['Description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [91]:
corpus

['medic imag apparatu use field indic e g iridolog sclerolog etc incorpor record softwar indic function purpos softwar',
 'medic diagnost apparatu test specifi condit subject matter test e g blood sugar level cancer cell dna etc incorpor record oper system softwar',
 'balanc bird toy',
 'imag intensifi tube',
 'sunglass pet',
 'water temperatur gaug',
 'exercis pulley',
 'automobil engin model toy',
 'remot control submarin toy',
 'magnet clip sunglass lens',
 'pork jerki',
 'medic devic use treat diagnos specifi diseas condit integr record oper system softwar sold unit',
 'softwar use calcul transfer store data relat diagnosi treatment eye disord sold compon ophthalm surgic apparatu',
 'medic imag apparatu incorpor medic imag softwar',
 'medic imag apparatu indic medic use e g diagnos medic condit use surgic procedur etc incorpor record softwar indic function purpos softwar',
 'medic imag apparatu indic medic use e g diagnos medic condit use surgic procedur etc incorpor record oper system softwar',
 'medic imag apparatu use field indic e g iridolog sclerolog etc incorpor record oper system softwar',
 'medic workstat compris comput hardwar softwar gather transmit patient imag data use surgic procedur',
 'simul steer control vehicl comput hardwar softwar',
 'basebal softbal train apparatu use sensor softwar analyz bat swing electron display result',
 'sport train apparatu featur electron sensor softwar analyz indic apparatu analyz e g muscl contract run speed bat swing etc electron display result',
 'turbin control system compris electron sensor relat softwar',
 'vehicl detect equip name display monitor comput imag sensor video camera oper system applic softwar detect vehicl locat',
 'free space optic transmiss system ethernet switch router softwar sold compon thereof separ name softwar adapt arrang oper instal test diagnos manag forgo telecommun equip',
 'support flat feet',
 'suspensori bandag',
 'spanish mackerel live',
 'capelin live',
 'autom process control system name micro processor base hardwar softwar use monitor statu industri machineri name turbin gener compressor',
 'autom process control system name micro processor base hardwar softwar use monitor statu industri process name power gener electr distribut oil ga process',
 'broadband power line commun system transfer broadband data electr power line compris comput hardwar softwar modem',
 'build secur system compris softwar hardwar provid pictur video alarm statu build plan inform remot station',
 'comput hardwar softwar sold unit test embed comput system',
 'comput hardwar softwar system track peopl object pet use gp data devic track peopl object pet',
 'day night vision system primarili compris day night sensor day night camera monitor',
 'electron commun system compris comput hardwar record softwar transmiss data two point',
 'global posit system gp consist comput comput softwar transmitt receiv network interfac devic',
 'offic electr power autom system compris comput hardwar wireless wire control download softwar autom indic autom e g applianc light hvac secur electr power etc',
 'home offic autom system compris wireless wire control control devic softwar light hvac secur safeti home offic monitor control applic',
 'home offic autom system compris comput hardwar wireless wire control download softwar autom indic autom e g applianc light hvac secur electr power etc',
 'home autom system compris comput hardwar wireless wire control download softwar autom indic autom e g applianc light hvac secur electr power etc',
 'offic autom system compris comput hardwar wireless wire control download softwar autom indic autom e g applianc light hvac secur electr power etc',
 'home autom hub compris voic activ speaker comput hardwar softwar indic function e g control network devic internet thing iot oper internet enabl connect light apparatu home secur alarm etc',
 'home autom hub compris voic activ speaker comput hardwar record softwar indic function e g control network devic internet thing iot oper internet enabl connect light apparatu home secur alarm etc',
 'home autom hub compris voic activ speaker comput hardwar download softwar indic function e g control network devic internet thing iot oper internet enabl connect light apparatu home secur alarm etc',
 'crystal sugar confectioneri',
 'couscou semolina',
 'prepar dish consist primarili meat also includ couscou',
 'electr warmer melt scent wax tart',
 'electr candl warmer',
 'fragranc dispens unit also featur night light',
 'non electr air diffus compris wick contain use emit scent lit sold without scent oil',
 'water power aromatherapi diffus compris shower bracket use emit scent shower sold without scent oil',
 'air diffus specifi use e g freezer aquarium etc',
 'aquarium air stone',
 'electr devic plug wall outlet heat element dispens indic use e g insect repel',
 'electr vapor household purpos',
 'electr batteri oper aromatherapi unit',
 'electr dispens air freshen',
 'candl warmer',
 'electr candl warmer',
 'fragranc lamp sold empti',
 'non electr aromatherapi diffus use shower',
 'air diffus aquarium',
 'air stone aquarium',
 'air diffus hydropon',
 'air pump hydropon',
 'water pump hydropon',
 'air diffus part refriger',
 'plug diffus insect repel',
 'plug diffus air fragranc',
 'vapor electr aromat oil diffus',
 'electr aromatherapi oil diffus',
 'non electr aromat oil diffus reed diffus',
 'plug diffus air deodor',
 'electr essenti oil diffus',
 'ultrason essenti oil diffus',
 'electr aromatherapi diffus',
 'tea light essenti oil diffus',
 'tealight essenti oil diffus',
 'soya bean past condiment',
 'soybean past',
 'cook dish consist primarili soybean past tofu doenjang jjiga',
 'pelmeni dumpl stuf meat',
 'pelmeni',
 'ramen japanes noodl base dish',
 'okonomiyaki japanes savori pancak',
 'okonomiyaki japanes savouri pancak',
 'savori pancak mix',
 'batter mix okonomiyaki japanes savori pancak',
 'korean style dri seawe roll contain cook rice gimbap',
 'gimbap korean rice dish',
 'soy bean past',
 'bean past',
 'hand oper tool reach grab handl small object',
 'electr pedicur tool',
 'electr manicur tool',
 'pedicur tool',
 'frame work art natur indic e g poster paint etc',
 'non metal hang closet organ specifi e g shoe sweater purs etc',
 'nitrogen gener equip compon name nitrogen gener associ nozzl sold unit',
 'oxygen concentr use fuel cell use heat ventil air condit light power system build',
 'explos actuat tool drive rivet',
 'thermal past',
 'reagent bear diagnost strip test breast milk medic veterinari use',
 'lye water food industri',
 'research analysi field econom econom polici',
 'busi research servic field indic field subject matter',
 'provid busi research servic name research dental patient insur inform dental offic',
 'busi research servic name provid analysi retail data specif busi locat',
 'line busi research servic allow user analyz opinion trend contain document internet',
 'shop research pose custom evalu qualiti servic deliv',
 'financi research',
 'financi research field financi instrument',
 'stem cell research servic',
 'research field hair care',
 'charit servic name provid comput softwar need exclud comput game softwar',
 'tea pot made preciou metal',
 'fingerstal offic use',
 'coat check servic',
 'corn starch deriv powder form make beverag',
 'valet tray valet box',
 'tea pot',
 'maintain patient medic record file',
 'provid temporari use line non download softwar applic specifi function program e g use databas manag use spreadsheet word process etc softwar content field specif field use',
 'provid temporari use web base softwar applic specifi function program e g use databas manag use spreadsheet word process etc softwar content field specif field use',
 'provid line non download softwar specifi function program e g use databas manag use spreadsheet word process etc softwar content field specif field use',
 'scientif research consult field indic scientif field e g genet',
 'coordin measur instrument',
 'scent oil use produc aroma heat',
 'power ice auger use ice fish',
 'utensil basket dishwash machin',
 'mangl',
 'hand oper salt grinder',
 'play suit',
 'baselay bottom',
 'video game develop servic',
 'provid inform relat comput technolog program via websit',
 'tuxedo rental',
 'hair moistur',
 'lip condition',
 'diagnost reagent medic use',
 'dietet confectioneri adapt medic purpos',
 'power oper blower',
 'pulp process machin',
 'spark plug land vehicl',
 'lanolin industri purpos',
 'sesam oil industri purpos',
 'anti nauseant',
 'arisaema root medic purpos',
 'tissu impregn skin cleanser',
 'boil oil industri purpos',
 'vehicl registr plate metal',
 'brake shoe vehicl',
 'curtain draw devic electr oper',
 'electr saw',
 'tractor tow fertil distributor',
 'central process unit cooler',
 'close circuit televis camera',
 'cloth protect chemic',
 'comput game programm download via internet',
 'comput motherboard',
 'data process equip',
 'cyclon separ',
 'massag gel medic purpos',
 'non medic pet shampoo',
 'prepar strip wax floor',
 'shave balm',
 'shine prepar plant leav',
 'metal fenc panel',
 'metal side',
 'metal valanc',
 'non electr wire common metal',
 'automat cash sort count machin',
 'armour plate metal build',
 'construct commerci build',
 'construct deck',
 'construct factori',
 'construct industri build',
 'construct oil pipelin',
 'construct repair mainten build provid inform relat thereto',
 'consult inform servic relat construct',
 'consult field basement waterproof',
 'consult relat instal mainten repair comput hardwar',
 'nail cap cat',
 'nail cap dog',
 'consult relat mainten comput hardwar',
 'consult relat repair comput hardwar',
 'rubber bumper pool ladder',
 'handrail metal swim pool',
 'bookbind materi',
 'bind materi book paper',
 'bookbind materi',
 'paper towel clean purpos',
 'trace needl draw',
 'squar draw',
 'draw tee squar',
 'ribbon typewrit',
 'wildlif manag',
 'legal consult relat licens',
 'legal consult relat licens indic specif good concept licens',
 'legal servic relat legal conveyanc',
 'electrostat spray disinfect build interior surfac',
 'residenti hotel servic',
 'hotel restaur reserv servic',
 'motel servic',
 'licens consult connect product bottl market sale wine wine relat beverag complianc exist feder state regul legal consult',
 'scent water make beverag',
 'commerci lobbi servic',
 'golf cours design',
 'assembl oil ga industri machin other',
 'assembl ga turbin combust engin other',
 'tea pot preciou metal',
 'bottl pharmaceut sold empti',
 'computer file manag',
 'legal servic relat licens',
 'licens advertis slogan',
 'licens architectur draw',
 'licens comput softwar',
 'pharmaceut product treatment infecti diseas',
 'electr razor',
 'cloth protect radiat',
 'speak tube',
 'download video game program',
 'smoke alarm',
 'lcd game machin',
 'tuna live',
 'bean meal',
 'natur perfumeri',
 'non medic skin toner',
 'metal skylight',
 'foil metal packag',
 'aluminum side',
 'cotter pin metal',
 'oil filter wrench',
 'construct repair airport airport facil',
 'construct repair hous',
 'construct repair residenti build hous',
 'construct build interior',
 'construct offic build',
 'construct porch',
 'construct repair mainten build',
 'construct repair mainten build provis inform relat thereto',
 'consult advisori servic relat repair mainten vacuum pump part thereof',
 'potato flour industri use',
 'gasolin refuel servic motor vehicl',
 'corn starch culinari purpos',
 'sago palm starch culinari purpos',
 'bag store hammock',
 'instal mainten burglar fire alarm',
 'instal mainten repair dental apparatu instrument',
 'instal mainten repair door fenc',
 'instal mainten repair fire detect apparatu',
 'instal mainten repair flare stack use oil industri',
 'instal mainten repair move staircas',
 'instal mainten repair move stairway',
 'instal repair mainten comput hardwar peripher comput support servic',
 'mainten clock',
 'mainten clock watch',
 'petrol refuel servic motor vehicl',
 'repair mainten film projector',
 'repair clock',
 'repair clock watch',
 'restor furnitur',
 'instal mainten repair fire detect system',
 'wearabl electron proxim sensor embed contact trace softwar specifi e g monitor alert social distanc distanc measur etc among wearer',
 'thermomet medic use embed softwar commun temperatur data track ill symptom',
 'softwar servic saa servic featur softwar analyz report self assess ill purpos specifi e g infecti diseas e coli outbreak etc contact trace',
 'cardiovascular pharmaceut prepar',
 'insecticid prepar',
 'pharmaceut product treatment viral diseas',
 'tile metal',
 'wire weld machin',
 'bolt cutter hand tool',
 'ditch bank blade hand tool',
 'comput mous',
 'sulphur',
 'raw natur canada balsam resin',
 'essenti oil canada balsam',
 'ammonia volatil alkali industri purpos',
 'expand clay substrat hydropon plant grow',
 'scent oil essenti oil use manufactur specifi product field use',
 'chemic prepar natur ion exchang resin',
 'chemic prepar natur ion exchang resin membran',
 'metal temper prepar',
 'vulcanis acceler',
 'dri ice carbon dioxid',
 'anim fodder addit natur fodder acidifi use manufactur anim fodder',
 'anim fodder addit natur fodder acidifi medic purpos',
 'rental robot appli spray coat',
 'rental robot build construct',
 'rental robot build mainten',
 'rental robot instal drywal',
 'rental robot paint',
 'rental robot power wash',
 'bread basket household purpos',
 'bucket made woven fabric',
 'box glass',
 'toothpast tube squeezer',
 'metal pin mount insect',
 'tungsten weight fish',
 'toy insect cage',
 'toy insect net',
 'toy model compound',
 'grill fish fillet',
 'soy milk beverag',
 'process brussel sprout',
 'sausag case',
 'frozen pizza',
 'taco sauc',
 'powder kill flea anim',
 'pharmaceut prepar treatment bone fractur',
 'sterilis substanc',
 'gel dermatolog use',
 'anti inflammatori prepar',
 'bacteri prepar medic purpos',
 'bacteri prepar veterinari purpos',
 'bacteriolog prepar medic purpos',
 'deodor cloth',
 'deodor textil',
 'greas medic veterinari purpos',
 'materi dental bridg',
 'materi dental crown',
 'materi repair teeth',
 'materi dental fill',
 'materi dental seal purpos',
 'medic mouth care prepar',
 'medic mouth treatment prepar',
 'petroleum jelli medic veterinari purpos',
 'pharmaceut prepar prevent osteoporosi',
 'pharmaceut prepar treatment hormon disord',
 'pharmaceut prepar treat allerg rhiniti',
 'pharmaceut prepar treat asthma',
 'pharmaceut product treatment cancer',
 'prepar prevent nail bite',
 'surgic plaster',
 'athlet foot prepar',
 'athlet foot powder',
 'athlet foot lotion',
 'provid temporari use line non download comput softwar use digit wallet',
 'furnitur part name countertop',
 'dish towel dri',
 'reed diffus compris scent oil also includ reed diffus contain',
 'provid web site featur temporari use non download softwar allow web site user upload post display onlin video share other entertain purpos',
 'provid line non download softwar gener cryptograph key receiv spend cryptocurr',
 'electron cigarett loung servic',
 'provid consum product recommend field indic subject matter field',
 'hand tool natur drum plug open',
 'hand tool natur jewelri clasp open',
 'hand tool natur pail lid open',
 'hand tool natur paint lid open',
 'manual oper contain open household domest use',
 'breast milk storag bag',
 'anim cruelti investig',
 'intraven iv hydrat therapi servic',
 'intraven iv vitamin therapi servic',
 'eras shield',
 'grape brandi distil armagnac region franc complianc law regul french govern',
 'grape brandi distil cognac region franc complianc law regul french govern',
 'make reserv book transport indic mode transport e g airplan train boat etc',
 'provid temporari use line non download firmwar specifi function program e g use databas manag use spreadsheet word process etc firmwar content field specif content field use',
 'fit cover ga oper power gener',
 'fit cover portabl electr power gener',
 'provid line cours instruct field specifi field e g scienc mathemat etc via websit',
 'provid cours instruct field specifi field e g scienc mathemat etc',
 'download audio file multimedia file text file e mail written document audio materi video materi game featur inform form download short educ train commun field human resourc develop promot employe retent career growth increas product employe employ',
 'placard plastic',
 'scalp micropigment servic',
 'placard wood',
 'mobil auto bodi repair servic natur paintless dent remov',
 'auto bodi repair servic natur paintless dent repair',
 'entertain natur pumpkin patch attract',
 'magnet levit desk toy',
 'provid review food food critic',
 'provid review restaur restaur critic',
 'provid temporari accommod anim pound',
 'provid temporari accommod halfway hous',
 'recept servic natur confer key guest temporari accommod',
 'recept servic natur manag arriv departur guest temporari accommod',
 'rental vacat accommod',
 'restaur review servic provid restaur critic',
 'temporari accommod provid dude ranch',
 'consult field landscap architectur',
 'landscap architectur',
 'medic treatment indic condit diseas e g osteoarthr cancer etc use cultur cell',
 'postnat care servic natur lactat consult',
 'postnat care servic natur massag therapi',
 'provid inform field landscap architectur',
 'provid substanc abus treatment halfway hous',
 'rental oxygen cylind fill medic purpos',
 'substanc abus treatment servic',
 'scent drawer liner paper',
 'perfum drawer line',
 'seal wafer',
 'wafer seal',
 'offic seal',
 'set squar draw',
 'draw set squar',
 'sheet paper take note',
 'ship contain cardboard',
 'ship contain made cardboard',
 'ship label paper',
 'ship label made paper',
 'paper ship label',
 'signboard paper',
 'signboard made paper',
 'commun via televis transmiss',
 'soup spoon',
 'christma garland',
 'demitass spoon',
 'download comput softwar access read track inform field indic subject matter inform e g patient medic record financi transact etc blockchain',
 'provid temporari use line non download softwar access read track inform field indic subject matter inform e g patient medic record financi transact etc blockchain',
 'dip pen',
 'pasteboard',
 'deep tissu massag',
 'plant soil',
 'topic skin spray cosmet purpos',
 'passeng lift',
 'hand oper hoe',
 'print citi directori',
 'paper babi bib',
 'download graphic novel',
 'solar power grill cook',
 'cape pet',
 'anti slip pad thong sandal',
 'scratch book draw',
 'chemic prepar seal plant wound',
 'cook oven',
 'provid consum product inform via internet',
 'steril servic person protect equip',
 'rental air purif equip',
 'glass work machin',
 'identif thread electr wire',
 'print color book',
 'print comic book',
 'plastic knob',
 'romper',
 'consult servic field internet market',
 'disinfect build interior surfac',
 'person chef servic',
 'electron feeder anim',
 'electr fli swatter',
 'clean brush automobil air condition',
 'hot stone massag',
 'grow media plant',
 'non electr water spray mop',
 'eyebrow tattoo servic',
 'chemic prepar prevent diseas affect cereal plant',
 'biostimul plant hormon',
 'biostimul plant nutrit prepar',
 'chemic prepar treat diseas affect vine plant',
 'motor hoe',
 'mother pearl unwork semi work',
 'wallpap brush',
 'sabr fenc',
 'acupressur slipper medic purpos',
 'live worm',
 'chemic prepar prevent diseas affect vine plant',
 'tea tree oil',
 'clean exterior surfac build provid inform relat thereto',
 'clean floor surfac',
 'clean offic build commerci premis',
 'clean rug',
 'clean storag tank',
 'clean textil',
 'clock watch mainten',
 'clock watch mainten servic',
 'calcium ascorb food industri',
 'waterproof coat use paint',
 'clock mainten',
 'clock mainten servic',
 'electr voltag tester pen',
 'tip paper cigarett',
 'custom manufactur make',
 'conduct pilat class',
 'hat rental',
 'soybean oil industri purpos',
 'age spot reduc cream',
 'clock repair servic',
 'insemin syring',
 'granul chicken bouillon',

In [92]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[2920,
  4566,
  3909,
  4237,
  3614,
  4011,
  2646,
  4626,
  1056,
  4532,
  3741,
  4345,
  1049,
  3057,
  4011,
  177,
  637,
  3057],
 [2920,
  3325,
  3909,
  4863,
  4256,
  134,
  4239,
  462,
  4863,
  2646,
  4626,
  2275,
  33,
  3734,
  637,
  4592,
  665,
  3741,
  4345,
  1049,
  108,
  2024,
  3057],
 [3995, 4064, 3082],
 [4566, 2648, 1539],
 [1224, 360],
 [4036, 3574, 3872],
 [2835, 2805],
 [2866, 2050, 2148, 3082],
 [3234, 4144, 4381, 3082],
 [2970, 2376, 1224, 2687],
 [4155, 146],
 [2920,
  1142,
  4237,
  874,
  4990,
  4256,
  2231,
  134,
  4155,
  1049,
  108,
  2024,
  3057,
  2610,
  1933],
 [3057,
  4237,
  3763,
  3770,
  4933,
  3936,
  1817,
  2402,
  1474,
  1570,
  385,
  2610,
  707,
  688,
  2298,
  3909],
 [2920, 4566, 3909, 4345, 2920, 4566, 3057],
 [2920,
  4566,
  3909,
  4011,
  2920,
  4237,
  2646,
  4626,
  4990,
  2920,
  134,
  4237,
  2298,
  2937,
  3741,
  4345,
  1049,
  3057,
  4011,
  177,
  637,
  3057],
 [2920,
  4566,
  3909,
  4011,
  2920,
  4237,
  2646,
  4626,
  4990,
  2920,
  134,
  4237,
  2298,
  2937,
  3741,
  4345,
  1049,
  108,
  2024,
  3057],
 [2920,
  4566,
  3909,
  4237,
  3614,
  4011,
  2646,
  4626,
  1056,
  4532,
  3741,
  4345,
  1049,
  108,
  2024,
  3057],
 [2920,
  2077,
  4759,
  823,
  1452,
  3057,
  154,
  3082,
  4716,
  4566,
  3936,
  4237,
  2298,
  2937],
 [3248, 4830, 4144, 2923, 823, 1452, 3057],
 [4713,
  2277,
  1598,
  3909,
  4237,
  3180,
  3057,
  3224,
  1779,
  3764,
  4941,
  2571,
  2420],
 [660,
  1598,
  3909,
  1014,
  4941,
  3180,
  3057,
  3224,
  4011,
  3909,
  3224,
  2646,
  4626,
  1220,
  4948,
  1776,
  2538,
  1779,
  3764,
  3741,
  4941,
  2571,
  2420],
 [4521, 4144, 2024, 4759, 4941, 3180, 1817, 3057],
 [2923,
  3498,
  1626,
  2743,
  2571,
  4278,
  823,
  4566,
  3180,
  3868,
  2386,
  108,
  2024,
  328,
  3057,
  3498,
  2923,
  1630],
 [690,
  3310,
  1932,
  2335,
  2024,
  2927,
  3424,
  2883,
  3057,
  2610,
  707,
  2372,
  1339,
  2743,
  3057,
  4710,
  2502,
  108,
  1820,
  4863,
  4990,
  4227,
  258,
  3067,
  1626],
 [315, 1740, 3871],
 [3400, 1054],
 [3809, 4159, 3720],
 [2527, 3720],
 [4181,
  4364,
  4144,
  2024,
  2743,
  1053,
  2512,
  4730,
  1452,
  3057,
  4237,
  4278,
  3687,
  4821,
  908,
  2743,
  4521,
  3973,
  981],
 [4181,
  4364,
  4144,
  2024,
  2743,
  1053,
  2512,
  4730,
  1452,
  3057,
  4237,
  4278,
  3687,
  4821,
  4364,
  2743,
  4021,
  3973,
  3261,
  4020,
  2641,
  3538,
  4364],
 [12,
  4021,
  1464,
  3146,
  2024,
  3770,
  12,
  3936,
  3261,
  4021,
  1464,
  4759,
  823,
  1452,
  3057,
  4064],
 [3122,
  193,
  2024,
  4759,
  3057,
  1452,
  389,
  2340,
  3868,
  4137,
  3687,
  3122,
  1939,
  1773,
  3234,
  4037],
 [823, 1452, 3057, 2610, 1933, 4863, 4585, 823, 2024],
 [823,
  1452,
  3057,
  2024,
  4172,
  1230,
  4763,
  360,
  4237,
  2741,
  3936,
  1142,
  4172,
  1230,
  4763,
  360],
 [3228,
  2234,
  2642,
  2024,
  2235,
  4759,
  3228,
  2234,
  3180,
  3228,
  2234,
  2386,
  4278],
 [4941, 3146, 2024, 4759, 823, 1452, 1049, 3057, 2335, 3936, 1512, 1130],
 [2615, 4613, 2024, 2741, 1407, 823, 823, 3057, 1561, 4824, 531, 2911, 1142],
 [735,
  3261,
  4021,
  4181,
  2024,
  4759,
  823,
  1452,
  1938,
  3480,
  4144,
  4953,
  3057,
  4181,
  4011,
  4181,
  2646,
  4626,
  1363,
  4722,
  121,
  193,
  3261,
  4021,
  3741],
 [1909,
  735,
  4181,
  2024,
  4759,
  1938,
  3480,
  4144,
  4144,
  1142,
  3057,
  4722,
  121,
  193,
  3624,
  1909,
  735,
  4278,
  4144,
  328],
 [1909,
  735,
  4181,
  2024,
  4759,
  823,
  1452,
  1938,
  3480,
  4144,
  4953,
  3057,
  4181,
  4011,
  4181,
  2646,
  4626,
  1363,
  4722,
  121,
  193,
  3261,
  4021,
  3741],
 [1909,
  4181,
  2024,
  4759,
  823,
  1452,
  1938,
  3480,
  4144,
  4953,
  3057,
  4181,
  4011,
  4181,
  2646,
  4626,
  1363,
  4722,
  121,
  193,
  3261,
  4021,
  3741],
 [735,
  4181,
  2024,
  4759,
  823,
  1452,
  1938,
  3480,
  4144,
  4953,
  3057,
  4181,
  4011,
  4181,
  2646,
  4626,
  1363,
  4722,
  121,
  193,
  3261,
  4021,
  3741],
 [1909,
  4181,
  179,
  4759,
  4323,
  4826,
  1555,
  823,
  1452,
  3057,
  4011,
  177,
  2646,
  4626,
  4144,
  531,
  1142,
  107,
  3501,
  2794,
  108,
  107,
  1645,
  4600,
  4722,
  3909,
  1909,
  193,
  4137,
  3741],
 [1909,
  4181,
  179,
  4759,
  4323,
  4826,
  1555,
  823,
  1452,
  1049,
  3057,
  4011,
  177,
  2646,
  4626,
  4144,
  531,
  1142,
  107,
  3501,
  2794,
  108,
  107,
  1645,
  4600,
  4722,
  3909,
  1909,
  193,
  4137,
  3741],
 [1909,
  4181,
  179,
  4759,
  4323,
  4826,
  1555,
  823,
  1452,
  4953,
  3057,
  4011,
  177,
  2646,
  4626,
  4144,
  531,
  1142,
  107,
  3501,
  2794,
  108,
  107,
  1645,
  4600,
  4722,
  3909,
  1909,
  193,
  4137,
  3741],
 [4129, 33, 1833],
 [1788, 889],
 [2085, 2857, 1407, 2235, 576, 2491, 529, 1788],
 [3261, 483, 1072, 2982, 3864, 424],
 [3261, 3927, 483],
 [4131, 488, 1933, 2491, 1014, 2234, 4722],
 [2665,
  3261,
  1505,
  2058,
  4759,
  538,
  454,
  4237,
  4973,
  2982,
  2418,
  2610,
  4830,
  2982,
  2641],
 [4036,
  4021,
  952,
  2058,
  4759,
  3733,
  4219,
  4237,
  4973,
  2982,
  3733,
  2610,
  4830,
  2982,
  2641],
 [1505, 2058, 4256, 4237, 2646, 4626, 2751, 4043, 3741],
 [4043, 1505, 4016],
 [3261,
  1142,
  947,
  2614,
  4812,
  2346,
  1065,
  488,
  4011,
  4237,
  2646,
  4626,
  3031,
  112],
 [3261, 3949, 654, 637],
 [3261, 1610, 108, 952, 1933],
 [3261, 488, 1505, 2052],
 [3927, 483],
 [3261, 3927, 483],
 [4131, 4349, 2610, 3432],
 [2665, 3261, 952, 2058, 4237, 3733],
 [1505, 2058, 4043],
 [1505, 4016, 4043],
 [1505, 2058, 3474],
 [1505, 4078, 3474],
 [4036, 4078, 3474],
 [1505, 2058, 751, 4342],
 [947, 2058, 3031, 112],
 [947, 2058, 1505, 4131],
 [3949, 3261, 1909, 2641, 2058],
 [3261, 952, 2641, 2058],
 [2665, 3261, 1909, 2641, 2058, 1552, 2058],
 [947, 2058, 1505, 744],
 [3261, 441, 2641, 2058],
 [819, 441, 2641, 2058],
 [3261, 952, 2058],
 [221, 4722, 441, 2641, 2058],
 [3201, 441, 2641, 2058],
 [4669, 3578, 758, 2945],
 [546, 758],
 [4058, 2857, 1407, 2235, 546, 758, 133, 1257, 2752],
 [875, 1864, 2445, 576],
 [875],
 [2603, 1387, 3088, 4730, 2857],
 [224, 1387, 1996, 2591],
 [224, 1387, 2482, 2591],
 [1996, 2591, 101],
 [4920, 101, 224, 1387, 1996, 2591],
 [1797, 3070, 4606, 3642, 2701, 454, 4058, 3649, 2219],
 [2219, 1797, 3649, 2857],
 [3447, 3578, 758],
 [3578, 758],
 [2583, 108, 4487, 1833, 3081, 939, 1902, 4763],
 [3261, 951, 4487],
 [3261, 2789, 4487],
 [951, 4487],
 [84, 4303, 1847, 4117, 4011, 2646, 4626, 310, 4525, 3741],
 [2665, 4075, 1577, 207, 4206, 4256, 2646, 4626, 770, 2805, 4932, 3741],
 [4486, 3973, 1626, 707, 2743, 4486, 3973, 188, 2129, 2610, 1933],
 [2560,
  2632,
  4237,
  4715,
  4592,
  4237,
  2346,
  1156,
  1505,
  134,
  4722,
  4021,
  2024,
  3122],
 [82, 1888, 4487, 929, 2196],
 [3242, 758],
 [3262, 4046, 3325, 331, 4863, 3820, 489, 2920, 2858, 4237],
 [19, 4036, 607, 4821],
 [3189, 1640, 3614, 4559, 4559, 4586],
 [1671, 3189, 1206, 3614, 4011, 3614, 4239, 462],
 [389, 1671, 3189, 1206, 2743, 3189, 3231, 4716, 4687, 1773, 3231, 735],
 [1671, 3189, 1206, 2743, 389, 1640, 4383, 3936, 203, 1671, 1630],
 [1464, 1671, 3189, 1206, 398, 1549, 3224, 3971, 318, 454, 4097, 107],
 [3201, 3189, 3563, 3286, 835, 2816, 1206, 3049],
 [128, 3189],
 [128, 3189, 3614, 128, 2885],
 [188, 4592, 3189, 1206],
 [3189, 3614, 1586, 3311],
 [4474, 1206, 2743, 389, 823, 3057, 2898, 4627, 823, 1261, 3057],
 [221, 2521, 4547, 3014, 4075],
 [1392, 735, 4237],
 [1023, 25, 1206],
 [4519, 17, 3709, 4917, 3251, 892, 4795],
 [4341, 1503, 4341, 4567],
 [221, 2521],
 [1199, 4716, 2920, 1049, 804],
 [389,
  371,
  4237,
  1464,
  2665,
  4953,
  3057,
  328,
  4256,
  177,
  4455,
  2646,
  4626,
  4237,
  4546,
  4227,
  4237,
  4967,
  522,
  4364,
  3741,
  3057,
  4322,
  3614,
  203,
  3614,
  4237],
 [389,
  371,
  4237,
  4182,
  4730,
  3057,
  328,
  4256,
  177,
  4455,
  2646,
  4626,
  4237,
  4546,
  4227,
  4237,
  4967,
  522,
  4364,
  3741,
  3057,
  4322,
  3614,
  203,
  3614,
  4237],
 [389,
  1464,
  2665,
  4953,
  3057,
  4256,
  177,
  4455,
  2646,
  4626,
  4237,
  4546,
  4227,
  4237,
  4967,
  522,
  4364,
  3741,
  3057,
  4322,
  3614,
  203,
  3614,
  4237],
 [1156, 3189, 2146, 3614, 4011, 1156, 3614, 2646, 4626, 2623],
 [3428, 1976, 2885],
 [2982, 2641, 4237, 329, 4010, 2346],
 [4021, 1248, 2070, 4237, 1248, 4895],
 [3746, 2272, 1836, 363],
 [1495],
 [2583, 108, 3113, 3282],
 [607, 242],
 [962, 2607],
 [3868, 1261, 3061, 1206],
 [389, 1773, 1817, 823, 2823, 4455, 4791, 1537],
 [3258, 4643],
 [1586, 3217],
 [4917, 4954],
 [3325, 3262, 2920, 4237],
 [443, 1833, 4710, 2920, 637],
 [4021, 108, 1605],
 [684, 4364, 363],
 [4893, 947, 4569, 2923],
 [782, 4821, 637],
 [3971, 2641, 4821, 637],
 [4272, 4071],
 [2859, 765, 2920, 637],
 [3609, 92, 875, 446],
 [2729, 2641, 4821, 637],
 [2923, 602, 3382, 4075],
 [1247, 770, 2923],
 [1885, 2500, 1142, 3261, 108],
 [3261, 1541],
 [1286, 3980, 4823, 2394],
 [2756, 4364, 1933, 4038],
 [4720, 4220, 341, 2386],
 [307, 4741, 2773],
 [823, 1261, 4740, 4953, 4791, 107],
 [823, 1584],
 [3936, 4364, 1626],
 [1989, 1339],
 [33, 3505, 2920, 637],
 [2665, 2920, 360, 2940],
 [2085, 331, 3864, 1883],
 [1886, 4320],
 [78, 2085, 901, 1788],
 [4075, 4040, 2814],
 [4075, 2433],
 [4075, 137],
 [2665, 3261, 3480, 1252, 4075],
 [309, 808, 3591, 289, 363],
 [3460, 3382, 4075, 3122],
 [3218, 2016, 3122],
 [3218, 936],
 [3218, 2240],
 [3218, 4821, 3122],
 [3218, 2641, 1059],
 [3218, 178, 2783, 3122, 389, 1773, 1817, 4463],
 [2146, 1773, 1206, 1817, 3218],
 [2146, 3614, 2982, 1618],
 [2146, 1817, 1820, 2783, 178, 823, 1452],
 [1599, 961, 3440],
 [1599, 961, 1466],
 [2146, 1817, 2783, 823, 1452],
 [2146, 1817, 178, 823, 1452],
 [2825, 2372, 4514, 1906],
 [1334, 4075, 3919, 4514],
 [3086, 2382],
 [4113, 2382, 1686, 2329],
 [3086, 2382],
 [2329, 2875, 1933, 637],
 [3458, 79, 2500],
 [2997, 2500],
 [2500, 1183, 2997],
 [3484, 1994],
 [734, 4227],
 [2543, 2146, 1817, 1424],
 [2543, 2146, 1817, 1424, 4011, 203, 542, 1671, 1424],
 [2543, 1206, 1817, 2543, 3648],
 [3767, 2963, 836, 3122, 1660, 4998],
 [3664, 2999, 1206],
 [2999, 4484, 2569, 1206],
 [3814, 1206],
 [1424,
  2146,
  4600,
  4672,
  4266,
  2147,
  2142,
  705,
  705,
  1817,
  4795,
  1080,
  3961,
  680,
  1528,
  3735,
  2543,
  2146],
 [2982, 4036, 892, 4795],
 [2016, 3868, 1206],
 [2201, 749, 3980],
 [2674, 2641, 3538, 4821, 363, 767],
 [2674, 3538, 4521, 1451, 2050, 767],
 [221, 2521, 3014, 4075],
 [4266, 82, 2610, 3432],
 [865, 804, 4227],
 [2543, 1206, 1817, 1424],
 [1424, 1193, 3714],
 [1424, 3872, 2500],
 [1424, 823, 3057],
 [82, 4672, 1474, 3505, 2231],
 [3261, 147],
 [307, 4741, 1520],
 [1637, 1539],
 [4953, 3868, 1261, 4455],
 [20, 4137],
 [3436, 1261, 363],
 [2299, 3720],
 [3578, 239],
 [4117, 4635],
 [2665, 2920, 875, 4084],
 [4075, 58],
 [4146, 4075, 3232],
 [3902, 2433],
 [1559, 4235, 4075],
 [2641, 2266, 722],
 [3218, 178, 54, 54, 985],
 [3218, 178, 1163],
 [3218, 178, 3664, 3122, 1163],
 [3218, 3122, 1660],
 [3218, 735, 3122],
 [3218, 2006],
 [3218, 178, 2783, 3122],
 [3218, 178, 2783, 3122, 1035, 1773, 1817, 4463],
 [2146, 2007, 1206, 1817, 178, 2783, 3299, 4078, 751, 2372],
 [4988, 1548, 4821, 4237],
 [1430, 3557, 1206, 4820, 2923],
 [4519, 17, 2176, 637],
 [2391, 290, 17, 2176, 637],
 [2623, 4933, 2431],
 [1820, 2783, 4157, 3684, 4137],
 [1820, 2783, 178, 3231, 3909, 2885],
 [1820, 2783, 178, 2441, 4040],
 [1820, 2783, 178, 3684, 3498, 3909],
 [1820, 2783, 178, 2140, 2140, 4237, 2641, 4821],
 [1820, 2783, 178, 775, 4847],
 [1820, 2783, 178, 775, 3599],
 [1820, 178, 2783, 823, 1452, 4634, 823, 315, 1206],
 [2783, 183],
 [2783, 183, 2761],
 [1404, 3557, 1206, 4820, 2923],
 [178, 2783, 4238, 3796],
 [178, 183],
 [178, 183, 2761],
 [3987, 2153],
 [1820, 2783, 178, 3684, 3498, 2024],
 [3592,
  4941,
  3465,
  3180,
  4585,
  1961,
  3458,
  3057,
  4256,
  2646,
  4626,
  4278,
  4151,
  2107,
  3373,
  3373,
  1976,
  3741,
  298,
  3613],
 [4444, 2920, 4237, 4585, 3057, 3146, 3574, 3936, 4172, 2466, 1579],
 [3057,
  1206,
  1758,
  1206,
  1014,
  3057,
  3224,
  3518,
  263,
  3997,
  2466,
  637,
  4256,
  2646,
  4626,
  3505,
  2231,
  2646,
  3840,
  4681,
  3741,
  1961,
  3458],
 [3522, 82, 2085],
 [373, 2085],
 [82, 4672, 1474, 1406, 2231],
 [4281, 4075],
 [3480, 2711, 363],
 [29, 4816, 2583, 4487],
 [2496, 1567, 3783, 2583, 4487],
 [823, 180],
 [291],
 [3492, 4117, 2158, 2561, 2040],
 [441, 2641, 2158, 2561],
 [2981, 4395, 2549, 4821, 637],
 [637, 4893, 3632, 3474, 901, 1613],
 [2982, 2641, 441, 2641, 4237, 4279, 4256, 4672, 3614, 4237],
 [2773, 2085, 4117, 2727, 1362, 2040],
 [2773, 2085, 4117, 2727, 1362, 2040, 3421],
 [4075, 2919, 2085],
 [719, 341],
 [4606, 1248, 2961, 1495],
 [7, 372, 1297, 4117, 372, 1877, 4237, 4279, 7, 372],
 [7, 372, 1297, 4117, 372, 1877, 2920, 637],
 [4643, 1081, 3764, 2963, 1023],
 [4643, 1081, 3122, 3218],
 [4643, 1081, 3122, 2783],
 [4643, 1081, 1820, 2645],
 [4643, 1081, 4525],
 [4643, 1081, 4021, 3165],
 [1546, 2272, 654, 637],
 [3138, 4547, 3096, 3406],
 [4567, 1028],
 [1843, 1539, 4591],
 [4075, 4235, 2664, 3031],
 [2059, 4886, 4895],
 [3082, 3031, 4135],
 [3082, 3031, 61],
 [3082, 2148, 2733],
 [2151, 4895, 100],
 [3447, 489, 4795],
 [4364, 741, 2558],
 [4855, 725],
 [3656, 4732],
 [1522, 1370],
 [4917, 2177, 3921, 7],
 [82, 2085, 1474, 4805, 1206],
 [723, 1521],
 [3505, 2847, 4237],
 [4272, 4246, 2085],
 [2773, 2085, 2920, 637],
 [2773, 2085, 2858, 637],
 [4165, 2085, 2920, 637],
 [744, 307],
 [744, 3428],
 [4771, 2920, 2858, 637],
 [2382, 3231, 302],
 [2382, 3231, 2238],
 [2382, 178, 2869],
 [2382, 3231, 4911],
 [2382, 3231, 4834, 637],
 [2920, 4396, 3311, 2085],
 [2920, 4396, 1474, 2085],
 [908, 2599, 2920, 2858, 637],
 [82, 2085, 698, 2788],
 [82, 2085, 1474, 447, 385],
 [82, 2085, 874, 2297, 4937],
 [82, 2085, 874, 3144],
 [82, 4672, 1474, 637],
 [2085, 698, 1599, 1250],
 [2298, 2143],
 [697, 3583, 2085],
 [697, 3583, 4917],
 [697, 3583, 2943],
 [389, 371, 4237, 1464, 2665, 4953, 823, 3057, 4237, 629, 4776],
 [2153, 751, 2743, 2649],
 [2857, 2875, 4606],
 [1552, 2058, 4759, 2982, 2641, 2491, 529, 1552, 2058, 454],
 [389,
  4182,
  3607,
  1014,
  371,
  4237,
  2665,
  4953,
  3057,
  398,
  4182,
  3607,
  1549,
  3675,
  3033,
  2571,
  3895,
  3868,
  810,
  767,
  1833,
  637],
 [389, 1464, 2665, 4953, 3057, 3973, 4592, 646, 4824, 4347, 1943],
 [4941, 3033, 4673, 1206],
 [389, 3111, 4672, 371, 3614, 4011, 4239, 462, 3614],
 [2583, 4487, 4117, 62, 947, 2105],
 [2583, 4487, 4117, 4683, 1896, 2105],
 [2583, 4487, 4117, 802, 2033, 2105],
 [2583, 4487, 4117, 4525, 2033, 2105],
 [3099, 108, 454, 2105, 654, 539, 4237],
 [3820, 489, 4294, 2623],
 [7, 4743, 3398],
 [1079, 1519, 2714, 3787, 1206],
 [1079, 1519, 4096, 3787, 1206],
 [1083, 186],
 [4094, 2334, 738, 3219, 2941, 369, 1080, 3957, 3735, 3195, 1271],
 [4094, 2334, 738, 1211, 2941, 369, 1080, 3957, 3735, 3195, 1271],
 [892, 2569, 1686, 1238, 4011, 1436, 1238, 2646, 4626, 3929, 1598, 4289, 3741],
 [389,
  371,
  4237,
  1464,
  2665,
  4953,
  2312,
  4256,
  177,
  4455,
  2646,
  4626,
  4237,
  4546,
  4227,
  4237,
  4967,
  522,
  4364,
  3741,
  2312,
  4322,
  3614,
  203,
  4322,
  3614,
  4237],
 [260, 1060, 3538, 108, 4021, 3973],
 [260, 1060, 4706, 3261, 4021, 3973],
 [389,
  1464,
  749,
  2046,
  3614,
  4256,
  3614,
  2646,
  4626,
  2022,
  556,
  3741,
  4791,
  1537],
 [389, 749, 2046, 3614, 4256, 3614, 2646, 4626, 2022, 556, 3741],
 [4953,
  101,
  804,
  1804,
  804,
  3054,
  804,
  2646,
  3357,
  744,
  4097,
  101,
  2382,
  3868,
  2382,
  1261,
  1014,
  1773,
  3251,
  4953,
  4230,
  897,
  1598,
  3146,
  3614,
  339,
  2310,
  3061,
  3960,
  2982,
  2641,
  3823,
  3831,
  1319,
  4672,
  2982,
  1879],
 [4418, 788],
 [2855, 429, 1206],
 [4418, 1548],
 [1439, 2069, 4239, 178, 1206, 4117, 2889, 3248, 4865],
 [2069, 4239, 178, 1206, 4117, 2889, 3248, 178],
 [1833, 4117, 204, 721, 2676],
 [2970, 1159, 4141, 3082],
 [389, 216, 607, 607, 2492],
 [389, 216, 4484, 4484, 2492],
 [389, 371, 1084, 7, 4236],
 [389, 371, 1084, 3012, 1163],
 [1861, 1206, 4117, 29, 646, 4038, 371, 1084],
 [1861, 1206, 4117, 4227, 2799, 862, 4038, 371, 1084],
 [4643, 1789, 1084],
 [4484, 216, 1206, 389, 4484, 2492],
 [371, 1084, 389, 1139, 19],
 [2146, 3614, 1653, 3872],
 [1653, 3872],
 [2920, 1474, 4011, 134, 2231, 2646, 4626, 1219, 637, 3741, 4237, 139, 4592],
 [1563, 3311, 1206, 4117, 3176, 2146],
 [1563, 3311, 1206, 4117, 33, 3787],
 [389, 1773, 3614, 1653, 3872],
 [389, 1521, 3518, 1474, 3012, 1163],
 [4643, 2560, 3235, 4911, 2920, 637],
 [1521, 3518, 1474, 1206],
 [2982, 4039, 1196, 2329],
 [3031, 4039, 1464],
 [4834, 2917],
 [2917, 4834],
 [735, 4834],
 [645, 2997, 2500],
 [2500, 645, 2997],
 [2097, 2329, 1169, 609],
 [4054, 454, 1208],
 [4054, 454, 4547, 1208],
 [4054, 2289, 2329],
 [4054, 2289, 4547, 2329],
 [2329, 4054, 2289],
 [632, 2329],
 [632, 4547, 2329],
 [3146, 4791, 341, 2335],
 [4411, 1212],
 [2357, 3989],
 [61, 1212],
 [4953,
  823,
  3057,
  4564,
  1035,
  4172,
  1773,
  3614,
  4011,
  4239,
  462,
  1773,
  2646,
  4626,
  4716,
  2920,
  1049,
  128,
  2748,
  3741,
  1561],
 [389,
  371,
  4237,
  1464,
  2665,
  4953,
  3057,
  4564,
  1035,
  4172,
  1773,
  3614,
  4011,
  4239,
  462,
  1773,
  2646,
  4626,
  4716,
  2920,
  1049,
  128,
  2748,
  3741,
  1561],
 [2206, 3847],
 [283],
 [1764, 3609, 33],
 [901, 4840],
 [1863, 875, 2963, 306, 637],
 [2348, 40],
 [2583, 108, 592],
 [1123, 2997, 3485],
 [2329, 973, 4142],
 [4953, 1932, 1542],
 [4741, 4021, 2151, 4058],
 [689, 360],
 [4272, 1250, 4565, 1383, 3382],
 [4991, 1686, 2500],
 [2773, 2085, 4834, 901, 2709],
 [4058, 640],
 [389, 3111, 4672, 1773, 4791, 107],
 [2184, 1206, 793, 4741, 1626],
 [4643, 1505, 1321, 1626],
 [1028, 4303, 363],
 [194, 323, 3261, 3480],
 [1123, 3594, 1686],
 [1123, 4174, 1686],
 [788, 1650],
 [3600],
 [2146, 1206, 3614, 107, 2147],
 [836, 3122, 1660, 4998],
 [793, 5, 1206],
 [4941, 4836, 7],
 [3261, 3437, 3207],
 [1933, 564, 2866, 1505, 4954],
 [3939, 4016, 33],
 [1613, 1634, 901],
 [2665, 3261, 4036, 2963, 3155],
 [2929, 3698, 1206],
 [2773, 2085, 698, 2231, 1489, 3763, 901],
 [2622, 901, 447],
 [2622, 901, 3511, 2085],
 [2773, 2085, 874, 2231, 1489, 1335, 901],
 [4820, 592],
 [689, 3920, 2568, 772, 4303],
 [4929, 564],
 [4406, 4040],
 [1353, 3675, 2920, 637],
 [3720, 976],
 [2773, 2085, 698, 2231, 1489, 1335, 901],
 [221, 2473, 2641],
 [1933, 4377, 4998, 3122, 389, 1773, 1817, 4463],
 [1933, 1883, 4998],
 [1933, 735, 3122, 2016, 322],
 [1933, 507],
 [1933, 4294, 3177],
 [1933, 3428],
 [183, 2761, 2783],
 [183, 2761, 2783, 1206],
 [3324, 1684, 607, 4821],
 [1618, 1023, 4237, 4525],
 [183, 2783],
 [183, 2783, 1206],
 [3261, 1046, 1031, 3847],
 [3119, 2329, 3033],
 [3286, 4279, 892],
 [3431, 4175, 1493],
 [340, 4643],
 [546, 2641, 4821, 637],
 [1763, 2598, 2973, 774],
 [183, 178, 1206],
 [4199, 4395],
 [2198, 2303, 2787],
 [2543, 3189, 1817, 1539, 4210, 2748],
 [2543, 2146, 1817, 341, 1193, 341, 1833, 660],
 [3431, 4869, 1565, 1979],
 [4375, 3613, 1424],
 [307, 178, 389, 1773, 1817, 4463],
 [1505, 1020, 2346, 4078, 4036, 1888],
 [3261, 2665, 3261, 1994],
 [1546, 3242, 2329],
 [2267, 4824],
 [3796, 4547, 2329],
 [4000, 117],
 [648, 2329],
 [4349, 3847],
 [3847, 4349],
 [4349, 1226, 3847],
 [4303, 1847, 1208],
 [2773, 2733, 3455, 3791],
 [2543, 3667],
 [546, 2609, 2773, 698, 3831, 546],
 [4877, 3210, 306, 2085, 1863, 3242, 4237],
 [875, 3217, 240],
 [4741, 725, 4706, 1634, 4081],
 [3203, 3038, 4425, 698, 390, 1027],
 [4706, 1524, 1555],
 [3067, 3424],
 [2386, 4771],
 [2386, 953],
 [3936, 2512],
 [2923, 1776, 2474],
 [1123, 3957, 2830],
 [910, 2623, 788, 654, 4237],
 [3500],
 [1123, 1932, 1542],
 [1123, 2047, 4455],
 [1123, 2344, 4174, 1686],
 [1123, 2457, 3830],
 [2500, 2474, 3932, 2869],
 [2664, 1123, 310],
 [1123, 3021, 944],
 [1240, 4237, 4364, 607, 4672],
 [2461, 4237, 4279, 2298, 1054],
 [3804, 2100, 1643, 2040],
 [4239, 4525, 306, 637],
 [1123, 1375],

In [93]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0 2920 ...  177  637 3057]
 [4863 4256  134 ...  108 2024 3057]
 [   0    0    0 ... 3995 4064 3082]
 ...
 [   0    0    0 ... 4237 4715 2453]
 [   0    0    0 ... 4117 1859 3524]
 [   0    0    0 ... 3131 3872 3741]]

In [94]:
embedded_docs[0]

array([   0,    0, 2920, 4566, 3909, 4237, 3614, 4011, 2646, 4626, 1056,
       4532, 3741, 4345, 1049, 3057, 4011,  177,  637, 3057])

In [132]:

from sklearn.preprocessing import LabelEncoder

In [133]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [141]:
# embedding_vector_features=40
# model=Sequential()
# model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model.add(LSTM(100))
# model.add(Dense(45,activation='softmax'))
# model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
# print(model.summary())

embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(46, activation='softmax'))  # Number of classes as output
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [142]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [143]:
# tf.convert_to_tensor(X_train, dtype=tf.float32)

In [144]:
model.fit(X_train,y_train, validation_data=(X_test,y_test),epochs=10, batch_size=64)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).